/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReputationBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "baseFee"
      | "feeReceiver"
      | "links"
      | "nftContract"
      | "oracleAddress"
      | "owner"
      | "renounceOwnership"
      | "requestLink"
      | "setOracleAddress"
      | "setVerificationStatus"
      | "successFee"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LinkRequested"
      | "LinkVerified"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "baseFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "links", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "nftContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestLink",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracleAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationStatus",
    values: [AddressLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "successFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "baseFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "links", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "successFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace LinkRequestedEvent {
  export type InputTuple = [
    oldAddress: AddressLike,
    newAddress: AddressLike,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    oldAddress: string,
    newAddress: string,
    proofHash: string
  ];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LinkVerifiedEvent {
  export type InputTuple = [
    oldAddress: AddressLike,
    newAddress: AddressLike,
    finalScore: BigNumberish
  ];
  export type OutputTuple = [
    oldAddress: string,
    newAddress: string,
    finalScore: bigint
  ];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
    finalScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationBridge extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationBridge;
  waitForDeployment(): Promise<this>;

  interface: ReputationBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  baseFee: TypedContractMethod<[], [bigint], "view">;

  feeReceiver: TypedContractMethod<[], [string], "view">;

  links: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean, string] & {
        newAddress: string;
        linkTimestamp: bigint;
        reputationScore: bigint;
        isVerified: boolean;
        proofHash: string;
      }
    ],
    "view"
  >;

  nftContract: TypedContractMethod<[], [string], "view">;

  oracleAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestLink: TypedContractMethod<
    [_oldAddress: AddressLike, _proofHash: BytesLike],
    [void],
    "payable"
  >;

  setOracleAddress: TypedContractMethod<
    [_newOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerificationStatus: TypedContractMethod<
    [_oldAddress: AddressLike, _status: boolean, _finalScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  successFee: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "baseFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "links"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean, string] & {
        newAddress: string;
        linkTimestamp: bigint;
        reputationScore: bigint;
        isVerified: boolean;
        proofHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nftContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "oracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestLink"
  ): TypedContractMethod<
    [_oldAddress: AddressLike, _proofHash: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setOracleAddress"
  ): TypedContractMethod<[_newOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerificationStatus"
  ): TypedContractMethod<
    [_oldAddress: AddressLike, _status: boolean, _finalScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "successFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "LinkRequested"
  ): TypedContractEvent<
    LinkRequestedEvent.InputTuple,
    LinkRequestedEvent.OutputTuple,
    LinkRequestedEvent.OutputObject
  >;
  getEvent(
    key: "LinkVerified"
  ): TypedContractEvent<
    LinkVerifiedEvent.InputTuple,
    LinkVerifiedEvent.OutputTuple,
    LinkVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "LinkRequested(address,address,bytes32)": TypedContractEvent<
      LinkRequestedEvent.InputTuple,
      LinkRequestedEvent.OutputTuple,
      LinkRequestedEvent.OutputObject
    >;
    LinkRequested: TypedContractEvent<
      LinkRequestedEvent.InputTuple,
      LinkRequestedEvent.OutputTuple,
      LinkRequestedEvent.OutputObject
    >;

    "LinkVerified(address,address,uint256)": TypedContractEvent<
      LinkVerifiedEvent.InputTuple,
      LinkVerifiedEvent.OutputTuple,
      LinkVerifiedEvent.OutputObject
    >;
    LinkVerified: TypedContractEvent<
      LinkVerifiedEvent.InputTuple,
      LinkVerifiedEvent.OutputTuple,
      LinkVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
